In [46]:
import pandas as pd
import numpy as np

In [47]:
df=pd.read_csv("synthetic_heart_disease_dataset.csv")

In [48]:
df.head()

,Age,Gender,Weight,Height,BMI,Smoking,Alcohol_Intake,Physical_Activity,Diet,Stress_Level,...,Diabetes,Hyperlipidemia,Family_History,Previous_Heart_Attack,Systolic_BP,Diastolic_BP,Heart_Rate,Blood_Sugar_Fasting,Cholesterol_Total,Heart_Disease
0,48,Male,78,157,26.4,Never,NaN,Sedentary,Healthy,Medium,...,0,1,1,0,104,99,71,165,200,0
1,35,Female,73,163,33.0,Never,Low,Active,Average,High,...,0,1,1,0,111,72,60,145,206,0
2,79,Female,88,152,32.3,Never,NaN,Moderate,Average,Medium,...,0,0,1,0,116,102,78,148,208,0
3,75,Male,106,171,37.4,Never,Moderate,Moderate,Average,Low,...,0,1,0,0,171,92,109,105,290,1
4,34,Female,65,191,18.5,Current,NaN,Sedentary,Healthy,Low,...,1,0,0,0,164,67,108,116,220,1

In [49]:
df.shape

(50000, 21)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    50000 non-null  int64
 1   Gender                 50000 non-null  object
 2   Weight                 50000 non-null  int64
 3   Height                 50000 non-null  int64
 4   BMI                    50000 non-null  float64
 5   Smoking                50000 non-null  object
 6   Alcohol_Intake         29891 non-null  object
 7   Physical_Activity      50000 non-null  object
 8   Diet                   50000 non-null  object
 9   Stress_Level           50000 non-null  object
 10  Hypertension           50000 non-null  int64
 11  Diabetes               50000 non-null  int64
 12  Hyperlipidemia         50000 non-null  int64
 13  Family_History         50000 non-null  int64
 14  Previous_Heart_Attack  50000 non-null  int64
 15  Systolic_BP            50000 non-null  int64
 16  Diastolic_BP           50000 non-null  int64
 17  Heart_Rate             50000 non-null  int64
 18  Blood_Sugar_Fasting    50000 non-null  int64
 19  Cholesterol_Total      50000 non-null  int64
 20  Heart_Disease          50000 non-null  int64
dtypes: float64(1), int64(14), object(6)
memory usage: 8.0+ MB

In [51]:
df.describe()

,Age,Weight,Height,BMI,Hypertension,Diabetes,Hyperlipidemia,Family_History,Previous_Heart_Attack,Systolic_BP,Diastolic_BP,Heart_Rate,Blood_Sugar_Fasting,Cholesterol_Total,Heart_Disease
count,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,54.46406,84.547520,174.460000,28.984284,0.299620,0.199260,0.251660,0.400500,0.099280,139.299580,89.528800,84.449560,124.493020,224.556360,0.463460
std,14.43809,20.213257,14.420379,6.367494,0.458096,0.399448,0.433971,0.490005,0.299041,23.083544,17.258063,14.491325,31.691507,43.157467,0.498668
min,30.00000,50.000000,150.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,60.000000,60.000000,70.000000,150.000000,0.000000
25%,42.00000,67.000000,162.000000,23.500000,0.000000,0.000000,0.000000,0.000000,0.000000,119.000000,75.000000,72.000000,97.000000,187.000000,0.000000
50%,54.00000,85.000000,174.000000,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000,139.000000,90.000000,85.000000,125.000000,225.000000,0.000000
75%,67.00000,102.000000,187.000000,34.500000,1.000000,0.000000,1.000000,1.000000,0.000000,159.000000,104.000000,97.000000,152.000000,262.000000,1.000000
max,79.00000,119.000000,199.000000,40.000000,1.000000,1.000000,1.000000,1.000000,1.000000,179.000000,119.000000,109.000000,179.000000,299.000000,1.000000

In [52]:
df.isnull().sum()

Age                          0
Gender                       0
Weight                       0
Height                       0
BMI                          0
Smoking                      0
Alcohol_Intake           20109
Physical_Activity            0
Diet                         0
Stress_Level                 0
Hypertension                 0
Diabetes                     0
Hyperlipidemia               0
Family_History               0
Previous_Heart_Attack        0
Systolic_BP                  0
Diastolic_BP                 0
Heart_Rate                   0
Blood_Sugar_Fasting          0
Cholesterol_Total            0
Heart_Disease                0
dtype: int64

In [53]:
df.columns

Index(['Age', 'Gender', 'Weight', 'Height', 'BMI', 'Smoking', 'Alcohol_Intake',
       'Physical_Activity', 'Diet', 'Stress_Level', 'Hypertension', 'Diabetes',
       'Hyperlipidemia', 'Family_History', 'Previous_Heart_Attack',
       'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Blood_Sugar_Fasting',
       'Cholesterol_Total', 'Heart_Disease'],
      dtype='object')

In [54]:
print("Smoking",df['Smoking'].unique())
print("alcohol_intake",df['Alcohol_Intake'].unique())
print("Physical_activity",df["Physical_Activity"].unique())
print("Diet",df["Diet"].unique())
print("Stress_level",df["Stress_Level"].unique())
print("Gender",df["Gender"].unique())

Smoking ['Never' 'Current' 'Former']
alcohol_intake [nan 'Low' 'Moderate' 'High']
Physical_activity ['Sedentary' 'Active' 'Moderate']
Diet ['Healthy' 'Average' 'Unhealthy']
Stress_level ['Medium' 'High' 'Low']
Gender ['Male' 'Female']

In [55]:
df = pd.get_dummies(
    df,
    columns=[
        'Gender',
        'Smoking',
        'Alcohol_Intake',
        'Physical_Activity',
        'Diet',
        'Stress_Level'
    ],
    drop_first=True
)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X=df.drop('Heart_Disease',axis=1)
y=df['Heart_Disease']

In [74]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=7)

##### Logistic regression

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
lg=LogisticRegression()
lg.fit(X_train,y_train)

C:\Users\GYANDEEP\Desktop\numpy\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [77]:
from sklearn.metrics import accuracy_score
y_pred=lg.predict(X_test)

In [78]:
accuracy_score(y_pred,y_test)

0.8886

##### Decision Tree

In [79]:
from sklearn.tree import DecisionTreeClassifier

In [80]:
dtc=DecisionTreeClassifier()

In [81]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [82]:
dy_pred=dtc.predict(X_test)

In [83]:
accuracy_score(dy_pred,y_test)

1.0

##### RandomForestClassifier

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
rfc=RandomForestClassifier()

In [86]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [87]:
ry_pred=rfc.predict(X_test)

In [88]:
accuracy_score(ry_pred,y_test)

1.0

##### KNN without scaling

In [89]:
from sklearn.neighbors import KNeighborsClassifier

In [91]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [92]:
ky_pred=knn.predict(X_test)

In [93]:
accuracy_score(ky_pred,y_test)

0.7021

In [173]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [175]:
scaler=StandardScaler()
knn=KNeighborsClassifier()
X_train_scaler=scaler.fit_transform(X_train)
X_test_scaler=scaler.fit_transform(X_test)

In [176]:
knn.fit(X_train_scaler,y_train)

KNeighborsClassifier()

In [177]:
ky_pred=knn.predict(X_test_scaler)

In [178]:
accuracy_score(ky_pred,y_test)

0.8611

#### SVM without scaling

In [ ]:
from sklearn.svm import

In [158]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)
sy_pred=svm.predict(X_test)

In [159]:
accuracy_score(sy_pred,y_test)

0.7363

##### SVM with scaling

In [110]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
svm=SVC()
scaler=StandardScaler()

In [112]:
X_train_scaler=scaler.fit_transform(X_train)
X_test_scaler=scaler.fit_transform(X_test)

svm.fit(X_train_scaler,y_train)
sy_pred=svm.predict(X_test_scaler)

In [114]:
accuracy_score(sy_pred,y_test)

0.941

#### Cross validation search

In [121]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [122]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
ry_pred=rfc.predict(X_test)

In [123]:
score=cross_val_score(rfc,X,y,cv=5)

In [124]:
print(score)
print(score.mean())

[1. 1. 1. 1. 1.]
1.0

#### GridSearchCV

In [125]:
from sklearn.model_selection import GridSearchCV

In [129]:
params={
    'n_estimators':[10,30,50,60,100],
    'max_depth':[4,7,8,9,None]
}

In [130]:
grid=GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=params,
    cv=5
)

In [131]:
grid.fit(X,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [4, 7, 8, 9, None],
                         'n_estimators': [10, 30, 50, 60, 100]})

In [132]:
print("Best Parameters:",grid.best_params_)
print("Best SCore:",grid.best_score_)

Best Parameters: {'max_depth': 7, 'n_estimators': 100}
Best SCore: 1.0

#### Features importances

In [133]:
importance_df=pd.DataFrame({
    'Feature':X.columns,
    'Importance':rfc.feature_importances_
})
print(importance_df.sort_values(by='Importance',ascending=False))

                        Feature  Importance
0                           Age    0.249496
13            Cholesterol_Total    0.240056
4                  Hypertension    0.210989
5                      Diabetes    0.147712
8         Previous_Heart_Attack    0.081638
3                           BMI    0.008711
12          Blood_Sugar_Fasting    0.008312
9                   Systolic_BP    0.007994
1                        Weight    0.007828
10                 Diastolic_BP    0.007688
11                   Heart_Rate    0.007459
2                        Height    0.007403
7                Family_History    0.001274
14                  Gender_Male    0.001204
16                Smoking_Never    0.001195
19   Physical_Activity_Moderate    0.001176
6                Hyperlipidemia    0.001156
24          Stress_Level_Medium    0.001142
17           Alcohol_Intake_Low    0.001135
23             Stress_Level_Low    0.001126
21                 Diet_Healthy    0.001119
18      Alcohol_Intake_Moderate    0.001061
15               Smoking_Former    0.001057
20  Physical_Activity_Sedentary    0.001050
22               Diet_Unhealthy    0.001016

### PipeLine with Logistic Regression

In [143]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [147]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

In [149]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())])

In [150]:
py_pred=pipe.predict(X_test)
accuracy_score(py_pred,y_test)

0.9256